#spring:
#  # 数据库配置
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/rag
#    username: root
#    password: 123456
logging:
  level:
    root: info